### ISSUE TITLE
Client secret is expired

### ISSUE THREAD

**Issue by alisrn** [zumwald/stateless-vsts-oauth#13]
Hello, I can't manage to refresh client secret. I have deleted the authorization from VSTS and tried to re-create it with `better-vsts-npm-auth` command but after I give the access, It again says client secret is expired.
`{"Error":"invalid_request","ErrorDescription":"Client secret is expired."}`

**Comment by kscharm** [comment]
I am receiving the same error

**Comment by zumwald** [comment]
see #12
