### ISSUE TITLE
Web App - Unavailable (403)

### ISSUE THREAD

**Issue by KyleBastien** [zumwald/stateless-vsts-oauth#8]
![image](https://user-images.githubusercontent.com/3861611/112892894-c6343c80-908e-11eb-996b-47df26f33798.png)

Looks like the site might be down?

**Comment by truepele** [comment]
I can see the same...

**Comment by chadius-maximus** [comment]
Confirming, same thing

**Comment by arjith** [comment]
Confirming the same

**Comment by KyleBastien** [comment]
Looks like this has been fixed, as per https://github.com/zumwald/better-vsts-npm-auth/issues/39
